export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const SELECT_SOURCE = 'SELECT_SOURCE';
export const SOURCE_HAS_ERRORED = 'SOURCE_HAS_ERRORED';
export const SOURCE_IS_LOADING = 'SOURCE_IS_LOADING';
